service: chainSpy-backend

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  chainInfo:
    handler: api/chainInfo/handler.main
    events:
      - http:
          path: /chaininfo
          method: get
